---
title: "R Notebook"
output: html_notebook
---

# data 

IPIP

https://github.com/automoto/big-five-data/blob/master/big_five_scores.csv


```{r}

library(tidyverse)
library(ggridges)
library(magrittr)
```
# data import 

```{r}
setwd("/Users/mm/Google Drive (xerroxcopy@gmail.com)/[G112]Pentagon/big-five-personality-test")
data_raw3 <- read_csv("input3/big_five_scores.csv")
View(data_raw3)
df3 <- data_raw3 %>% 
  pivot_longer(cols = ends_with("score"), names_to = "bigfive", values_to = "value") %>% 
  mutate(sex = recode(sex, `1` = "Male", `2` = "Female"))
```

# plot

```{r}
df3 %>% 
  filter(age < 80) %>% 
  ggplot(aes(x = age, y = value)) +
  stat_density_2d(
    geom = "raster",
    aes(fill = after_stat(density)),
    contour = FALSE
  ) +
  scale_fill_viridis_c() +
  geom_smooth(aes(color = sex)) +
  scale_color_manual(values = c("black", "blue")) +
  facet_grid(cols = vars(bigfive))+
  theme_linedraw() +
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0)) +
  theme(legend.position = "none")

ggsave("output/plot/all_IPIP_age-value~gender.png", width=25/3, height=7/3, unit="in", dpi=600)
```

